Fixes for gcc 15 errors about implicit declarations
* Define _GNU_SOURCE globally with AC_USE_SYSTEM_EXTENSIONS
* Use FD_CLOEXEC instead of O_CLOEXEC

Some of the errors:

src/channel.c:126:44: error: ‘O_CLOEXEC’ undeclared (first use in this function); did you mean ‘FD_CLOEXEC’?
  126 |   if (fcntl(channel->audio_fd[0], F_SETFL, O_CLOEXEC | O_NONBLOCK) < 0)

src/channel.c:286:17: error: implicit declaration of function ‘be16toh’ [-Wimplicit-function-declaration]
  286 |   header->len = be16toh(be);

src/crypto.c:208:11: error: implicit declaration of function ‘htobe32’ [-Wimplicit-function-declaration]
  208 |   nonce = htobe32(cipher->nonce);

src/crypto.c:566:3: error: implicit declaration of function ‘clock_gettime’ [-Wimplicit-function-declaration]
  566 |   clock_gettime(CLOCK_MONOTONIC, &start_ts);